--batch-file play.list
-f "bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best[height<=480]"
--merge-output-format mp4
--write-auto-sub
--all-subs
--external-downloader aria2c
--external-downloader-args "-x 16 -k 1M"
--embed-thumbnail
--add-metadata
--output downloads/%(title)s-%(id)s.%(ext)s
--continue
